# Generated by Django 2.1.2 on 2018-10-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181027_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.TextField(),
        ),
    ]
